version: '3.1'
services:
  stats-server:
    build: stats-service2/stats-server
    image: stats
    container_name: stats-service
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - ewm-service
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=stats-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: main-service
    image: ewm-service
    container_name: ewm-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
        - SPRING_DATASOURCE_USERNAME=ewm
        - SPRING_DATASOURCE_PASSWORD=ewm
        - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
        - "5431:5432"
    environment:
        - POSTGRES_DB=ewm-db
        - POSTGRES_USER=ewm
        - POSTGRES_PASSWORD=ewm